access_log  /var/log/nginx/access.log;
error_log   /var/log/nginx/error.log warn;

upstream backend {
    server backend:8888;
}

server {
    listen 80;
    server_name ${HOST};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://${HOST}$request_uri;
    }
}

server {
    listen 443                                ssl;
	  root                              /front/dist;
    index                              index.html;
    server_name                           ${HOST};
    client_max_body_size                      50M;

    location ~ /\. {
        deny all;
        return 404;
    }

    ssl_certificate /etc/letsencrypt/live/${HOST}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${HOST}/privkey.pem;

    location / {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_redirect     off;

        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;
    }
}


