RETRY_AFTER_SECONDS = "30"
APPLICATION_ERROR = "application_error"
NOT_FOUND = "not_found"
SERVICE_UNAVAILABLE = "service_unavailable"
EXTERNAL_UNAVAILABLE = "external_service_unavailable"
CACHE_UNAVAILABLE = "cache_unavailable"
DATABASE_UNAVAILABLE = "database_unavailable"
VALIDATION_ERROR = "validation_error"
INTERNAL_ERROR = "internal_error"
UNMAPPED_LOG = "unmapped application error: type=%s %s cause=%s"
APPLICATION_LOG = "%s %s cause=%s"
INFRASTRUCTURE_LOG = "infrastructure error: type=%s %s cause=%s"
EXTERNAL_LOG = "external service unavailable: type=%s %s cause=%s"
CACHE_LOG = "cache unavailable: type=%s %s cause=%s"
DATABASE_LOG = "database unavailable: type=%s %s cause=%s"
VALIDATION_LOG = "validation_error %s fields=%d first=%s"
UNHANDLED_LOG = "unhandled exception: %s"
